### ISSUE TITLE
username resolver doesn't work on getUserProfilePhotos method

### ISSUE THREAD

**Issue by Besatnias** [GochoMugo/tgfancy#2]
If I try `bot.sendMessage("@myusername", "message")`; it gets sent,

if I try `bot.getUserProfilePhotos("@myusername").then((res)=>{bot.sendPhoto(msg.chat.id, res.photos[0][0].file_id});` I get a 400 user not found error

if I try `bot.getUserProfilePhotos(msg.from.id).then((res)=>{bot.sendPhoto(msg.chat.id, res.photos[0][0].file_id});` I get a nice picture in my inbox.

**Comment by GochoMugo** [comment]
The chat ID is **not** resolved since we have **not** added the function i.e. `TelegramBot#getUserProfilePhotos()` to the list of fancied functions with chat ID resolution. See [the list](https://github.com/GochoMugo/tgfancy/blob/6a24433f797d75ccf8d0707366c63b6e2a2c410b/lib/client.js#L30).

The missing functions include:

* getUserProfilePhotos()
* sendContact()
* setGameScore()
* getGameHighScores()

I will add support for them asap.

**Comment by GochoMugo** [comment]
Fixed in **v0.7.0**.
