### ISSUE TITLE
Add fanciness: Virtual Hosting (to host multiple bots on same port)

### ISSUE THREAD

**Issue by ohenepee** [GochoMugo/tgfancy#9]
Using `node-http-proxy` from nodejitsu would be awesome!

**Comment by GochoMugo** [comment]
Are we responsible for creating the multiple bots?

**Comment by ohenepee** [comment]
Yes!!

**Comment by GochoMugo** [comment]
So, basically this would entail the library spawning a new process for each of the bots, automatically configure the *master* process to proxy to these new *child* processes, and manage these children like any decent process manager i.e. restart failed process etc.

We might decide to integrate a process manager, such as PM2 or forever, and use a proxy library for that. But don't you think it is too much work and effort on the part of the *parent* process. I would highly suggest that you use dedicated utilities, such as NginX for proxying, PM2 or Docker for process management, etc. Such utilities are focused on providing their respective utilities in a depth that I do **not** believe this library would be able to achieve.

Is this feature really really necessary. I think it is **nice fanciness** but *too expensive for our taste* :wink:. Otherwise, thanks for your interest in this feature.

**Comment by ohenepee** [comment]
Well, one part I think and love about frameworks is not to over-configure and not to be over-dependent.. I mean its always better to have a single tool for everything, than NodeJS, Docker, NginX :(

**Comment by GochoMugo** [comment]
And I agree a better user experience may be offered by a framework, until you want to switch one of the inner component with a better one.

Sorry, if you are hoping for a complete solution with tgfancy, you will not find it here. Sorry. Closing this now.
